package lol.duckyyy.client.screen;

import lol.duckyyy.client.CoduhLinkClient;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagsProvider;
import net.minecraft.ChatFormatting;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.layouts.FrameLayout;
import net.minecraft.client.gui.layouts.GridLayout;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.TextColor;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.util.ARGB;
import net.minecraft.util.CommonColors;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Blocks;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.*;

public class KeybindHelpScreen extends Screen {
    private boolean open;
    private String pageReadable = "Home";
    private String pageSubheading = "Select a category to keep reading...";
    private Component heading;
    private Component subheading;
    private Component helpText = Component.literal("View this screen at any time with Ctrl + ").withColor(TextColor.YELLOW).withStyle(ChatFormatting.ITALIC).append(Component.empty().append(Component.keybind("key.coduhlink.help").withColor(TextColor.GOLD).withStyle(ChatFormatting.ITALIC, ChatFormatting.BOLD)));
    private Component creditText = Component.literal("Reference Generated by CoduhLink").withColor(TextColor.GRAY).withStyle(ChatFormatting.ITALIC);
    private Map<String, String> readablePages = new HashMap<>();
    private Map<String, String> pageSubheadings = new HashMap<>();
    private Button closeButton;
    private Button backButton;
    private int ticks = 0;
    private int seconds = 0;
    private boolean canClose = false;
    private int safeTextHeight = 0;
    private int headingSafeHeight = 0;
    private String page = "home";
    private String lastPage = "home";
    private GuiGraphicsExtractor g;
    private final List<String> phrases = List.of("what's your favorite color?", "do you know the muffin man?", "and the duck walked up to the lemonade stand", "got any grapes?", "got milk?");
    private final String randomPhrase = this.phrases.get((int) (Math.random() * phrases.size()));

    public KeybindHelpScreen(String page) {
        super(Component.literal("Help Screen"));
        this.open = true;
        this.page = page;
    }

    @Override
    public void init() {
        super.init();
        if(Component.keybind("key.coduhlink.help").getString().equalsIgnoreCase(".")) {
            this.helpText = this.helpText.copy().append(Component.literal(" (Period)").withColor(TextColor.GOLD).withStyle(ChatFormatting.ITALIC));
        }

        this.readablePages.put("home", "Home");
        this.readablePages.put("keybinds", "Keybinds");
        this.readablePages.put("smelting", "Smelting Fuel Guide");
        this.readablePages.put("hi", "Hi");

        this.pageSubheadings.put("home", "Select a category to keep reading...");
        this.pageSubheadings.put("keybinds", "Basic keybindings needed to play Minecraft");
        this.pageSubheadings.put("tiers", ":D");
        this.pageSubheadings.put("smelting", "You can use various types of fuel to smelt items using a Furnace block.");
        this.pageSubheadings.put("hi", ":D");

        this.heading = Component.literal(String.format("Reference - %s", this.readablePages.get(this.page))).withColor(TextColor.GOLD).withStyle(ChatFormatting.BOLD);
        this.subheading = Component.literal(this.pageSubheadings.get(this.page)).withColor(TextColor.GRAY).withStyle(ChatFormatting.ITALIC);

        int buttonWidth = 150;
        int buttonHeight = 20;

        net.minecraft.client.gui.layouts.GridLayout grid = new GridLayout();
        grid.defaultCellSetting().padding(4,4,4,4);
        GridLayout.RowHelper helper = grid.createRowHelper(2);

        if(!this.page.equalsIgnoreCase("home")) {
            this.closeButton = (Button) helper.addChild(Button.builder(Component.literal("Back"), b -> {
                this.page = "home";
                this.pageReadable = "Home";
                this.pageSubheading = "Select a category to keep reading...";
            }).build(), 1);
        }

        this.closeButton = (Button) helper.addChild(Button.builder(Component.literal("Close this Screen"), b -> {
            this.open = false;
            this.minecraft.gui.setScreen(null);
        }).build(), this.page.equalsIgnoreCase("home") ? 2 : 1);


        grid.arrangeElements();
        FrameLayout.alignInRectangle(grid, 0, this.height - 50, this.width, 30, 0.5F, 0.25F);
        grid.visitWidgets(this::addRenderableWidget);
    }

    @Override
    public boolean shouldCloseOnEsc() {
        return true;
    }

    @Override
    public boolean isPauseScreen() {
        return true;
    }

    public void drawHeading(GuiGraphicsExtractor graphics) {
        int textY = 10;
        graphics.centeredText(this.font, this.heading, this.width/2, textY, 0xFFFFFFFF);
        textY+=20;
        graphics.centeredText(this.font, this.subheading, this.width/2, textY, 0xFFFFFFFF);
        textY+=20;
        graphics.centeredText(this.font, this.helpText, this.width/2, textY, 0xFFFFFFFF);
        this.safeTextHeight = textY;
        this.headingSafeHeight = textY+=20;
    }

    public void drawCredit(GuiGraphicsExtractor graphics) {
        int textY = this.height-20;
        graphics.centeredText(this.font, this.creditText, this.width/2, textY, 0xFFFFFFFF);
    }

    public Component keybindCategory(String category) {
        return Component.literal(category).withColor(TextColor.GOLD).withStyle(ChatFormatting.BOLD);
    }

    public Component keybind(String action) {
        Component actionName = Component.translatable(String.format("key.%s", action));
        if(actionName.getString().toLowerCase().contains("sneak")) actionName = actionName.copy().append(" (Crouch)");
        return Component.empty().append(actionName).append(Component.empty().append(Component.literal(" » "))).append(Component.empty().append(Component.keybind(String.format("key.%s", action)).withColor(TextColor.GOLD)));
    }

    public Component descriptionText(String text) {
        return Component.literal(text).withStyle(ChatFormatting.GRAY, ChatFormatting.ITALIC);
    }

    public Component hotbarKeybind() {
        Component actionName = Component.literal("Hotbar Slot 1-9");
        return Component.empty().append(actionName).append(Component.empty().append(Component.literal(" » "))).append(Component.empty().append(Component.literal("1 - 9").withColor(TextColor.GOLD)));
    }

    public void drawPage(GuiGraphicsExtractor graphics) {
        this.safeTextHeight = this.headingSafeHeight;
        int keybindSpacer = 20;
        int hRulePadding = 300;

        this.heading = Component.literal(String.format("Reference - %s", this.readablePages.get(this.page))).withColor(TextColor.GOLD).withStyle(ChatFormatting.BOLD);
        this.subheading = Component.literal(this.pageSubheadings.get(this.page)).withColor(TextColor.GRAY).withStyle(ChatFormatting.ITALIC);


        if(page.equalsIgnoreCase("home")) {
            net.minecraft.client.gui.layouts.GridLayout grid = new GridLayout();
            grid.defaultCellSetting().padding(4,4,4,4);
            GridLayout.RowHelper helper = grid.createRowHelper(1);

            helper.addChild(Button.builder(Component.literal("Keybinds"), b -> {
                this.lastPage = "home";
                this.page = "keybinds";
            }).build());
            helper.addChild(Button.builder(Component.literal("Equipment Tiers"), b -> {
                this.lastPage = "home";
                this.page = "tiers";
            }).build());
            helper.addChild(Button.builder(Component.literal("Smelting Fuel Guide"), b -> {
                this.lastPage = "home";
                this.page = "smelting";
            }).build());
            helper.addChild(Button.builder(Component.literal("hi :)"), b -> {
                this.lastPage = "home";
                this.page = "hi";
            }).build());

            grid.arrangeElements();
            FrameLayout.alignInRectangle(grid, 0, this.safeTextHeight+keybindSpacer, this.width, this.height-300, 0.5F, 0.25F);
            grid.visitWidgets(this::addRenderableWidget);
        } else if(page.equalsIgnoreCase("keybinds")) {
            graphics.centeredText(this.font, this.keybindCategory("Movement"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("forward"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("left"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("right"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("back"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("jump"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("sprint"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("sneak"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);

            this.safeTextHeight+=keybindSpacer;
            graphics.horizontalLine(hRulePadding,this.width-hRulePadding, this.safeTextHeight, 0xFFFFFF4D);

            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybindCategory("Gameplay"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("use"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.descriptionText("If an item is in your offhand, it may take usage priority over your main hand."), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("attack"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("pickItem"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);

            this.safeTextHeight+=keybindSpacer;
            graphics.horizontalLine(hRulePadding,this.width-hRulePadding, this.safeTextHeight, 0xFFFFFF4D);

            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybindCategory("Inventory"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.hotbarKeybind(), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("inventory"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("swapOffhand"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
            this.safeTextHeight+=keybindSpacer;
            graphics.centeredText(this.font, this.keybind("drop"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        } else if (this.page.equalsIgnoreCase("tiers")) {
            this.safeTextHeight+=10;
            int spacer = 20;
            this.equipmentTierText(Items.WOODEN_PICKAXE, "Wood", 0xbc8a2d, graphics, this.safeTextHeight);
            this.safeTextHeight+= spacer;
            this.equipmentTierCraftedWith(List.of(Items.OAK_PLANKS, Items.STICK), 0xbc8a2d, graphics, this.safeTextHeight);
            this.safeTextHeight+=spacer;
            this.equipmentTierCanBreak(List.of(Items.STONE, Items.COAL_ORE, Items.IRON_ORE), 0xbc8a2d, graphics, this.safeTextHeight);
            this.safeTextHeight+=spacer;
            List<Item> planks = new ArrayList<>();
            for(Item item : BuiltInRegistries.ITEM.stream().toList()) {
                if(item.getDefaultInstance().tags().toList().contains(ItemTags.PLANKS)) planks.add(item);
            }
            this.equipmentTierRepairedWith(planks, 0xbc8a2d, graphics, this.safeTextHeight, ItemTags.PLANKS);

            this.safeTextHeight+= (int) Math.round(spacer*1.5);
            this.equipmentTierText(Items.STONE_PICKAXE, "Stone", 0x5b5957, graphics, this.safeTextHeight);
            this.safeTextHeight+= spacer;
            this.equipmentTierCraftedWith(List.of(Items.COBBLESTONE, Items.COBBLED_DEEPSLATE, Items.BLACKSTONE, Items.STICK), 0x5b5957, graphics, this.safeTextHeight);
            this.safeTextHeight+=spacer;
            this.equipmentTierCanBreak(List.of(Items.STONE, Items.COAL_ORE, Items.IRON_ORE), 0x5b5957, graphics, this.safeTextHeight);
            this.safeTextHeight+=spacer;

            List<Item> stones = new ArrayList<>();
            for(Item item : BuiltInRegistries.ITEM.stream().toList()) {
                if(item.getDefaultInstance().tags().toList().contains(ItemTags.STONE_TOOL_MATERIALS)) stones.add(item);
            }
            this.equipmentTierRepairedWith(stones, 0x5b5957, graphics, this.safeTextHeight, ItemTags.STONE_TOOL_MATERIALS);

            this.safeTextHeight+= (int) Math.round(spacer*1.5);
            this.equipmentTierText(Items.IRON_PICKAXE, "Iron", 0xb2b2b2, graphics, this.safeTextHeight);
            this.safeTextHeight+= spacer;
            this.equipmentTierCraftedWith(List.of(Items.IRON_INGOT, Items.STICK), 0xb2b2b2, graphics, this.safeTextHeight);
            this.safeTextHeight+=spacer;
            this.equipmentTierCanBreak(List.of(Items.REDSTONE_ORE, Items.GOLD_ORE, Items.DIAMOND_ORE, Items.EMERALD_ORE), 0xb2b2b2, graphics, this.safeTextHeight);
            this.safeTextHeight+=spacer;

            this.equipmentTierRepairedWith(List.of(Items.IRON_INGOT), 0xb2b2b2, graphics, this.safeTextHeight, null);

            this.safeTextHeight+= (int) Math.round(spacer*1.5);
            this.equipmentTierText(Items.DIAMOND_PICKAXE, "Diamond", 0xA1FBE8, graphics, this.safeTextHeight);
            this.safeTextHeight+= spacer;
            this.equipmentTierCraftedWith(List.of(Items.DIAMOND, Items.STICK), 0xA1FBE8, graphics, this.safeTextHeight);
            this.safeTextHeight+=spacer;
            this.equipmentTierCanBreak(List.of(Items.OBSIDIAN, Items.ANCIENT_DEBRIS), 0xA1FBE8, graphics, this.safeTextHeight);
            this.safeTextHeight+=spacer;

            this.equipmentTierRepairedWith(List.of(Items.DIAMOND), 0xA1FBE8, graphics, this.safeTextHeight, null);

            this.safeTextHeight+= (int) Math.round(spacer*1.5);
            this.equipmentTierText(Items.NETHERITE_PICKAXE, "Netherite", 0x5A575A, graphics, this.safeTextHeight);
            this.safeTextHeight+= spacer;
            this.equipmentTierCraftedWith(List.of(Items.DIAMOND_PICKAXE, Items.NETHERITE_INGOT, Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE, Items.SMITHING_TABLE), 0x5A575A, graphics, this.safeTextHeight);
            this.safeTextHeight+=spacer;
            this.equipmentTierCanBreak(List.of(Items.OBSIDIAN, Items.ANCIENT_DEBRIS), 0x5A575A, graphics, this.safeTextHeight);
            this.safeTextHeight+=spacer;

            this.equipmentTierRepairedWith(List.of(Items.NETHERITE_INGOT), 0x5A575A, graphics, this.safeTextHeight, null);
        } else if(this.page.equalsIgnoreCase("smelting")) {
            Map<Item, Integer> fuels = new HashMap<>();
            fuels.put(Items.COAL, 8);
            fuels.put(Items.CHARCOAL, 8);
            fuels.put(Items.LAVA_BUCKET, 100);
            fuels.put(Items.COAL_BLOCK, 80);
            fuels.put(Items.DRIED_KELP_BLOCK, 20);
            fuels.put(Items.BLAZE_ROD, 12);


            this.fuelItemTable(fuels, 0x161616, 0x282828, graphics, this.safeTextHeight);

            this.safeTextHeight+=20;

            Map<Item, List<String>> cooksBlocks = new HashMap<>();
            cooksBlocks.put(Items.FURNACE, List.of("Everything"));
            cooksBlocks.put(Items.BLAST_FURNACE, List.of("Ores"));
            cooksBlocks.put(Items.SMOKER, List.of("Food"));
            cooksBlocks.put(Items.CAMPFIRE, List.of("Meats, Fish, Potatoes, Kelp"));
            cooksBlocks.put(Items.SOUL_CAMPFIRE, List.of("Meats, Fish, Potatoes, Kelp"));
            cooksBlocks.put(Items.FLINT_AND_STEEL, List.of("Burnt mobs drop cooked meat"));

            this.smeltingBlockTable(cooksBlocks, 0x161616, 0x282828, graphics, this.safeTextHeight);

        } else if(this.page.equalsIgnoreCase("hi")) {
            graphics.centeredText(this.font, Component.literal("hi :D"), this.width/2, (this.height/2)-7, 0xFFFFFFFF);
            List<TextColor> colors = List.of(TextColor.WHITE, TextColor.GOLD, TextColor.RED, TextColor.GRAY, TextColor.AQUA, TextColor.BLACK, TextColor.YELLOW, TextColor.LIGHT_PURPLE, TextColor.GREEN, TextColor.DARK_RED, TextColor.DARK_PURPLE, TextColor.DARK_GREEN, TextColor.DARK_GRAY, TextColor.DARK_BLUE, TextColor.DARK_AQUA);
            graphics.centeredText(this.font, Component.literal(this.randomPhrase).withStyle(ChatFormatting.ITALIC).withColor(colors.get((int) (Math.random() * colors.size()))), this.width/2, (this.height/2)+7, 0xFFFFFFFF);
        }

    }

    private void smeltingBlockTable(Map<Item, List<String>> items, int headerColor, int rowColor, GuiGraphicsExtractor graphics, int y) {
        int xOffset = 100;
        int innerXOffset = xOffset;
        int itemXOffset = 170;

        // Heading
        graphics.fill((this.width/2)-(180), y-2,(this.width/2)+(180),(y-4)+22, ARGB.color(180, headerColor));
        graphics.centeredText(this.font, Component.literal("Cooking Method").withColor(TextColor.WHITE), (this.width/2)-xOffset, y+4, 0xFFFFFFFF);
        graphics.centeredText(this.font, Component.literal("Used For").withColor(TextColor.WHITE), (this.width/2)+xOffset, y+4, 0xFFFFFFFF);

        this.safeTextHeight+=24;

        // Rows
        int i = 0;
        for(Item item : items.keySet()) {
            i+=1;
            y+=20;
            this.safeTextHeight+=24;
            List<String> cooksTags = items.get(item).stream().map(String::toUpperCase).toList();

            // Alternating Row Background
            int alpha = (i % 2 == 0) ? 140 : 180;
            int bgColor = ARGB.color(alpha, rowColor);
            graphics.fill((this.width/2)-(180), y-2,(this.width/2)+(180),(y-4)+22, bgColor);

            // Fuel Item Display
//            graphics.centeredText(this.font, Component.literal("Fuel Item").withColor(TextColor.WHITE), (this.width/2)-xOffset, y+4, 0xFFFFFFFF);
            int itemWidth = this.font.width(Component.literal(item.getDefaultInstance().getItemName().getString()));
            graphics.text(this.font, Component.literal(item.getDefaultInstance().getItemName().getString()), (this.width/2)-innerXOffset-(itemWidth/2)+8, y+4, 0xFFFFFFFF);
            graphics.item(item.getDefaultInstance(), ((this.width/2)-itemXOffset)-4,y);

            // Number of items text
            graphics.centeredText(this.font, Component.literal(String.join(", ", cooksTags)).withColor(TextColor.WHITE), (this.width/2)+xOffset, y+4, 0xFFFFFFFF);
        }
    }

    private void fuelItemTable(Map<Item, Integer> items, int headerColor, int rowColor, GuiGraphicsExtractor graphics, int y) {
        int xOffset = 100;
        int innerXOffset = xOffset;
        int itemXOffset = 170;

        // Heading
        graphics.fill((this.width/2)-(180), y-2,(this.width/2)+(180),(y-4)+22, ARGB.color(180, headerColor));
        graphics.centeredText(this.font, Component.literal("Fuel Item").withColor(TextColor.WHITE), (this.width/2)-xOffset, y+4, 0xFFFFFFFF);
        graphics.centeredText(this.font, Component.literal("Smelts # of Items").withColor(TextColor.WHITE), (this.width/2)+xOffset, y+4, 0xFFFFFFFF);

        this.safeTextHeight+=24;

        // Rows
        int i = 0;
        for(Item item : items.keySet()) {
            i+=1;
            y+=20;
            this.safeTextHeight+=24;
            int smeltCount = items.get(item);

            // Alternating Row Background
            int alpha = (i % 2 == 0) ? 140 : 180;
            int bgColor = ARGB.color(alpha, rowColor);
            graphics.fill((this.width/2)-(180), y-2,(this.width/2)+(180),(y-4)+22, bgColor);

            // Fuel Item Display
//            graphics.centeredText(this.font, Component.literal("Fuel Item").withColor(TextColor.WHITE), (this.width/2)-xOffset, y+4, 0xFFFFFFFF);
            int itemWidth = this.font.width(Component.literal(item.getDefaultInstance().getItemName().getString()));
            graphics.text(this.font, Component.literal(item.getDefaultInstance().getItemName().getString()), (this.width/2)-innerXOffset-(itemWidth/2)+8, y+4, 0xFFFFFFFF);
            graphics.item(item.getDefaultInstance(), ((this.width/2)-itemXOffset)-4,y);

            // Number of items text
            graphics.centeredText(this.font, Component.literal(String.format("x%s", smeltCount)).withColor(TextColor.WHITE), (this.width/2)+xOffset, y+4, 0xFFFFFFFF);
        }
    }

    private void equipmentTierText(Item item, String tier, int tierColor, GuiGraphicsExtractor graphics, int y) {
        int tierWidth = this.font.width(tier);
        graphics.fill((this.width/2)-(180), y-2,(this.width/2)+(180),(y-4)+22, ARGB.color(80, 0x000000));
        graphics.item(item.getDefaultInstance(), (this.width/2)-tierWidth,y);
        graphics.text(this.font, Component.literal(tier).withStyle(ChatFormatting.BOLD).withColor(tierColor), (this.width/2), y+4, 0xFFFFFFFF);
    }

    private void equipmentTierCraftedWith(List<Item> items, int tierColor, GuiGraphicsExtractor graphics, int y) {
        graphics.fill((this.width/2)-(180), y-2,(this.width/2)+(180),(y-4)+22, ARGB.color(150, tierColor));
        graphics.centeredText(this.font, Component.literal("Crafted with").withColor(TextColor.WHITE), (this.width/2)-100, y+4, 0xFFFFFFFF);
        int xOffset = 100;
            for(Item item : items) {
                graphics.item(item.getDefaultInstance(), (this.width/2)+xOffset,y);
                xOffset-=20;
            }

    }

    private void equipmentTierCanBreak(List<Item> items, int tierColor, GuiGraphicsExtractor graphics, int y) {
        graphics.fill((this.width/2)-(180), y-2,(this.width/2)+(180),(y-4)+22, ARGB.color(100, tierColor));
        graphics.centeredText(this.font, Component.literal("Can break").withColor(TextColor.WHITE), (this.width/2)-100, y+4, 0xFFFFFFFF);
        int xOffset = 100;
        for(Item item : items) {
            graphics.item(item.getDefaultInstance(), (this.width/2)+xOffset,y);
            xOffset-=20;
        }
    }

    private void equipmentTierRepairedWith(List<Item> items, int tierColor, GuiGraphicsExtractor graphics, int y, @Nullable TagKey<Item> tag) {
        graphics.fill((this.width/2)-(180), y-2,(this.width/2)+(180),(y-4)+22, ARGB.color(150, tierColor));
        graphics.centeredText(this.font, Component.literal("Repaired with").withColor(TextColor.WHITE), (this.width/2)-100, y+4, 0xFFFFFFFF);
        int xOffset = 100;
        if(tag != null) {
            @Nullable String t = tag.getName().getString().replace("minecraft:", "").toUpperCase();
            for(Item item : items.subList(0,Math.min(items.size(), 3))) {
                graphics.item(item.getDefaultInstance(), (this.width/2)+xOffset,y);
                xOffset-=20;
            }
        } else {
        for(Item item : items.subList(0,Math.min(items.size(), 5))) {
            graphics.item(item.getDefaultInstance(), (this.width/2)+xOffset,y);
            xOffset-=20;
        }
        }
    }

    public void resetDrawing(GuiGraphicsExtractor graphics) {
        this.minecraft.gui.setScreen(new KeybindHelpScreen(this.page));
        this.ticks = 0;
        if(!this.page.equals("tiers")) this.drawHeading(graphics);
        this.drawCredit(graphics);
        this.drawPage(graphics);
    }

    @Override
    public void extractRenderState(@NotNull GuiGraphicsExtractor graphics, int mouseX, int mouseY, float delta) {
        this.g = graphics;
        super.extractRenderState(graphics, mouseX, mouseY, delta);
        if(!this.page.equals("tiers")) this.drawHeading(graphics);
        this.drawCredit(graphics);
        this.drawPage(graphics);
    }

    @Override
    public void tick() {
        super.tick();

        ticks+=1;
        if((ticks % 20) == 0) {
            seconds+=1;
            ticks = 0;
        }
        if(CoduhLinkClient.HELP_KEYBIND.isDown() && this.minecraft.hasControlDown() && this.open) {
            this.open = false;
            this.minecraft.gui.setScreen(null);
        }

//        int ENABLE_BACK_BUTTON_SECONDS = 3;
//        int ENABLE_BACK_BUTTON_TICKS = ENABLE_BACK_BUTTON_SECONDS*20;
//
//        if(ticks < ENABLE_BACK_BUTTON_TICKS) {
//            this.closeButton.setMessage(Component.literal(String.format("%ss...", ENABLE_BACK_BUTTON_SECONDS-seconds)));
//            this.canClose = false;
//        } else {
//            this.closeButton.active = true;
//            this.canClose = true;
//            this.closeButton.setMessage(Component.literal("Close this Screen"));
//        }

        if(!this.page.equals(this.lastPage)) {
            if(this.g != null) {
                this.lastPage = this.page;
                this.resetDrawing(this.g);
            }
        }
    }
}
