package lol.duckyyy.client.screen;

import lol.duckyyy.client.CoduhLinkClient;
import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.TextColor;
import net.minecraft.resources.Identifier;
import org.jetbrains.annotations.NotNull;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

public class KeybindHelpScreen extends Screen {
    private boolean open;
    private final Component heading = Component.literal("Keybind Reference").withColor(TextColor.GOLD).withStyle(ChatFormatting.BOLD);
    private final Component subheading = Component.literal("Basic keybindings needed to play Minecraft.").withColor(TextColor.GRAY).withStyle(ChatFormatting.ITALIC);
    private Component helpText = Component.literal("View this screen at any time with Ctrl + ").withColor(TextColor.YELLOW).withStyle(ChatFormatting.ITALIC).append(Component.empty().append(Component.keybind("key.coduhlink.help").withColor(TextColor.GOLD).withStyle(ChatFormatting.ITALIC, ChatFormatting.BOLD)));
    private Component creditText = Component.literal("Reference Generated by CoduhLink").withColor(TextColor.GRAY).withStyle(ChatFormatting.ITALIC);
    private Button backButton;
    private int ticks = 0;
    private int seconds = 0;
    private boolean canClose = false;
    private int safeTextHeight = 0;

    public KeybindHelpScreen() {
        super(Component.literal("Minecraft Basic Keybinds"));
        this.open = true;
    }

    @Override
    public void init() {
        super.init();
        if(Component.keybind("key.coduhlink.help").getString().equalsIgnoreCase(".")) {
            this.helpText = this.helpText.copy().append(Component.literal(" (Period)").withColor(TextColor.GOLD).withStyle(ChatFormatting.ITALIC));
        }

        int buttonWidth = 150;
        int buttonHeight = 20;

        this.backButton = (Button) this.addRenderableWidget(Button.builder(Component.literal("Close this Screen"), b -> {
            this.open = false;
            this.minecraft.gui.setScreen(null);
        }).bounds((this.width/2)-(buttonWidth/2), this.height-50, buttonWidth, buttonHeight).build());
        this.backButton.active = false;
    }

    @Override
    public boolean shouldCloseOnEsc() {
        return canClose;
    }

    @Override
    public boolean isPauseScreen() {
        return true;
    }

    public void drawHeading(GuiGraphicsExtractor graphics) {
        int textY = 10;
        graphics.centeredText(this.font, this.heading, this.width/2, textY, 0xFFFFFFFF);
        textY+=20;
        graphics.centeredText(this.font, this.subheading, this.width/2, textY, 0xFFFFFFFF);
        textY+=20;
        graphics.centeredText(this.font, this.helpText, this.width/2, textY, 0xFFFFFFFF);
        this.safeTextHeight = textY;
    }

    public void drawCredit(GuiGraphicsExtractor graphics) {
        int textY = this.height-20;
        graphics.centeredText(this.font, this.creditText, this.width/2, textY, 0xFFFFFFFF);
    }

    public Component keybindCategory(String category) {
        return Component.literal(category).withColor(TextColor.GOLD).withStyle(ChatFormatting.BOLD);
    }

    public Component keybind(String action) {
        Component actionName = Component.translatable(String.format("key.%s", action));
        if(actionName.getString().toLowerCase().contains("sneak")) actionName = actionName.copy().append(" (Crouch)");
        return Component.empty().append(actionName).append(Component.empty().append(Component.literal(" » "))).append(Component.empty().append(Component.keybind(String.format("key.%s", action)).withColor(TextColor.GOLD)));
    }

    public Component descriptionText(String text) {
        return Component.literal(text).withStyle(ChatFormatting.GRAY, ChatFormatting.ITALIC);
    }

    public Component hotbarKeybind() {
        Component actionName = Component.literal("Hotbar Slot 1-9");
        return Component.empty().append(actionName).append(Component.empty().append(Component.literal(" » "))).append(Component.empty().append(Component.literal("1 - 9").withColor(TextColor.GOLD)));
    }

    public void drawKeybindArea(GuiGraphicsExtractor graphics) {
        this.safeTextHeight+=30;
        int keybindSpacer = 20;
        int hRulePadding = 300;

        graphics.centeredText(this.font, this.keybindCategory("Movement"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("forward"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("left"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("right"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("back"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("jump"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("sprint"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("sneak"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);

        this.safeTextHeight+=keybindSpacer;
        graphics.horizontalLine(hRulePadding,this.width-hRulePadding, this.safeTextHeight, 0xFFFFFF4D);

        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybindCategory("Gameplay"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("use"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.descriptionText("If an item is in your offhand, it may take usage priority over your main hand."), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("attack"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("pickItem"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);

        this.safeTextHeight+=keybindSpacer;
        graphics.horizontalLine(hRulePadding,this.width-hRulePadding, this.safeTextHeight, 0xFFFFFF4D);

        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybindCategory("Inventory"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.hotbarKeybind(), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("inventory"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("swapOffhand"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);
        this.safeTextHeight+=keybindSpacer;
        graphics.centeredText(this.font, this.keybind("drop"), this.width/2, this.safeTextHeight, 0xFFFFFFFF);

    }

    @Override
    public void extractRenderState(@NotNull GuiGraphicsExtractor graphics, int mouseX, int mouseY, float delta) {
        super.extractRenderState(graphics, mouseX, mouseY, delta);
        this.drawHeading(graphics);
        this.drawCredit(graphics);
        this.drawKeybindArea(graphics);
    }

    @Override
    public void tick() {
        super.tick();
        ticks+=1;
        if((ticks % 20) == 0) {
            seconds+=1;
        }
        if(CoduhLinkClient.HELP_KEYBIND.isDown() && this.minecraft.hasControlDown() && this.open) {
            this.open = false;
            this.minecraft.gui.setScreen(null);
        }

        int ENABLE_BACK_BUTTON_SECONDS = 3;
        int ENABLE_BACK_BUTTON_TICKS = ENABLE_BACK_BUTTON_SECONDS*20;

        if(ticks < ENABLE_BACK_BUTTON_TICKS) {
            this.backButton.setMessage(Component.literal(String.format("%ss...", ENABLE_BACK_BUTTON_SECONDS-seconds)));
            this.canClose = false;
        } else {
            this.backButton.active = true;
            this.canClose = true;
            this.backButton.setMessage(Component.literal("Close this Screen"));
        }
    }
}
